system:
  debug: true
  cache: data/cache
  version: "v24.09.29"
site:
  name: Chancel's Memo
  theme: mdui-theme-primary-pink 
  theme-accent: mdui-theme-accent-light-pink
memo:
  max_size: 5 # Mb
  id_defalt_length: 4
  id_max_length: 12
  expire: 0 # 0 indicates never expires


  