system:
  cache: cache/
site:
  name: Chancel's Memo
  theme: mdui-theme-primary-pink 
  theme_accent: mdui-theme-accent-pink
memo:
  max_size: 5 # Mb
  id_defalt_length: 4
  id_max_length: 12
  expire: 0 # the unit is second, set 0 indicates never expires


  